### ISSUE TITLE
Unclear choices in the new mail going out.

### ISSUE THREAD

**Issue by twish** [ourstudio-se/viruskoll#95]
The new choices that you have in the mail going out are pretty unclear and open for interpretation. I believe that this could impact the quality of the data you are gathering. 

![image](https://user-images.githubusercontent.com/5931183/78220293-88bfc200-74c1-11ea-92ee-bef0772c7476.png)

I am not an expert in forms och how to formulate those, but the ones in use now are hard to understand what to enter.

Otherwise, a great initiative with the site!

**Comment by alexerlandsson** [comment]
Thank you for the feedback!

You're right, the choices in the mail are unclear. Neither are we experts in copywriting so this kind of feedback is strongly appreciated.

We have now changed the mail to only include one option and changed the copy.  Here is an example of how the mail going out tomorrow will look like:

<img width="767" alt="Screen Shot 2020-04-03 at 14 56 20" src="https://user-images.githubusercontent.com/10596315/78363537-3a431e00-75bc-11ea-8394-e775f0ef6d6f.png">

Thank you!
